# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Functional Gibberish"
email: aaron@flexile.co
description: >- # this means to ignore newlines until "baseurl:"
  It doesn't mean anything, but it works
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://functionalgibberish.com" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:year-:month-:day-:title/
excerpt_separator: <!--more-->

footer-links:
  dribbble:
  email: aaron@flexile.co
  facebook:
  flickr:
  github: ahayman
  instagram:
  linkedin: aaron-hayman
  pinterest:
  rss: rss 
  twitter: 
  stackoverflow: users/1147934/aaron-hayman
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus:

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: :compressed

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"


kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/